---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by louqiangqiang.
--- DateTime: 2024/2/22 14:48
--- 参数1：topN个数
---
--- articleKey：interactive:article
---
local topLike = KEYS[1]
-- 获取要获取的top N数量
local topN = tonumber(ARGV[1])

local exist=redis.call("EXISTS", topLike)
if exist == 1 then
    -- 遍历所有格式为"interactive:article:ID"的key
    local articleKeys = redis.call("KEYS", "interactive:article:*")
    for i = 1, #articleKeys, 1 do
        local articleKey = articleKeys[i]
        local likeCnt = tonumber(redis.call("HGET", articleKey, "like_cnt"))

        -- 如果like_cnt存在，则将其添加到有序集合"topLike"中，其中文章ID作为成员，like_cnt作为分数
        if likeCnt then
            redis.call("ZADD", topLike, likeCnt, articleKey)
        end
    end
    -- 设置10分钟过期时间
    redis.call('EXPIRE', topLike,'600')
    return 1
else
    return 0
end